name: Sync test.py from testdev to main

on:
  push:
    branches:
      - testdev
  workflow_dispatch:  # Enables manual trigger from GitHub Actions

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to ensure all branches are available

      - name: Fetch All Branches
        run: |
          git fetch origin testdev  # Ensure we fetch testdev branch
          git branch -a  # Debugging: Check if testdev exists

      - name: Checkout main Branch
        run: git checkout main

      - name: Copy test.py from testdev
        run: |
          git checkout origin/testdev  # Explicitly reference the remote branch
          git add test.py
          git commit -m "Updated test.py from testdev"
          git push origin main
