name: Sync test.py from testdev to main

on:
  push:
    branches:
      - testdev  # Trigger when test.py is updated in testdev
  workflow_dispatch:  # Enables manual trigger from GitHub Actions

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Checkout main Branch
        run: git checkout main

      - name: Copy test.py from testdev
        run: |
          git checkout testdev -- test.py
          git add test.py
          git commit -m "Updated test.py from testdev"
          git push origin main
